### ISSUE TITLE
Cannot provide file arguments

### ISSUE THREAD

**Issue by stefandrissen** [bertjohnson/CSSCompare#1]
Both file argurments are ignored and overwritten to point to your dropbox red and blue.

**Comment by bertjohnson** [comment]
Thank you very much for the report.  That was leftover from testing and shouldn't have been included.  Version 2.3 is now uploaded (source and release), correcting that issue.  Thanks again!

**Comment by crutchcorn** [comment]
BTW, trying to keep discussion here rather than on an open issue or whatnot.

This is AMAZING. I just found this today and already helped with a massive CSV file. Really impressive and super useful stuff, thank you

**Comment by bertjohnson** [comment]
Thanks crutchcorn! Glad you found it useful.
